spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 819428ebda4254458e971e3d9bb89822
            client-secret: ySzHWh5333VN2ktUNVaqvrZPnvVSZZoX
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: https://pin-toss.com/api/oauth/callback/kakao
#            redirect-uri: http://localhost:8080/api/oauth/callback/kakao
            scope: account_email
            provider: kakao
          naver:
            client-id: ntP6_ogtZLkuD6J774IT
            client-secret: 9cIj0Lo1b_
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: https://pin-toss.com/api/oauth/callback/naver
#            redirect-uri: http://localhost:8080/api/oauth/callback/naver
            scope: email, mobile
            provider: naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
