spring:
  config:
    active:
      on-profile: local
    import: application-jwt.yaml, application-nice.yaml, application-oauth.yaml
  application:
    name : giftmall
  #  sql:
  #    init:
  #      data-locations: classpath:sql/data.sql
  datasource:
#    url: jdbc:mariadb://pintossmall2.cafe24.com:3306/pintossmall2?serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#    username: pintossmall2
#    password: cho459800
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/pintoss_auth?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        #        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
#        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type:
    org.hibernate.orm.jdbc.bind: trace
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MARIADB;DATABASE_TO_UPPER=FALSE;NON_KEYWORDS=USER
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.MariaDBDialect
