spring:
  config:
    active:
      on-profile: local
    import: application-jwt.yaml, application-nice.yaml, application-oauth.yaml, application-gmail.yaml, galaxia-test.yaml
  application:
    name : giftmall
  #  sql:
  #    init:
  #      data-locations: classpath:sql/data.sql
  datasource:
#    username: root
#    password: 12341234
#    url: jdbc:mariadb://localhost:3306/pintoss?useUnicode=yes&characterEncoding=UTF-8
    username: pintoss
    password: cho459800
    url: jdbc:mariadb://pintoss-db.ch2uwekqo8yv.ap-northeast-2.rds.amazonaws.com:3306/pintoss?useUnicode=true&characterEncoding=utf8mb4&connectionCollation=utf8mb4_general_ci

    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        connection:
          CharSet: utf8mb4
          charsetEncoding: utf8mb4
          useUnicode: true
        #        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
#        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type:
    org.hibernate.orm.jdbc.bind: trace
