name: Docker Build and Deploy

on:
  push:
    branches:
      - dev # Action 트리거 브랜치

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Submodule
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode Gmail Credentials and create noreply.json
        env:
          GOOGLE_GMAIL: ${{secrets.NOREPLY_JSON}}
        run: |
          mkdir -p src/main/resources
          echo "$GOOGLE_GMAIL" | base64 --decode > src/main/resources/noreply.json

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build --exclude-task test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 디렉토리와 파일 구조 확인
      - name: Check Current Directory
        run: |
          echo "Current Directory:"
          pwd
          echo "Files and Folders:"
          ls -al

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/pintoss-auth:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/pintoss-auth:latest
            sudo docker rm -f pintoss-auth
            sudo docker run -d -p 8080:8080 --name pintoss-auth ${{ secrets.DOCKER_HUB_USERNAME }}/pintoss-auth
            sudo docker image prune -a -f
