name: Gradle Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode Gmail Credentials and create noreply.json
        env:
          GOOGLE_GMAIL: ${{ secrets.GOOGLE_GMAIL }}
        run: |
          mkdir -p src/test/resources
          echo "$GOOGLE_GMAIL" | base64 --decode > src/test/resources/noreply.json

      - name: Process Test Resources
        run: ./gradlew processTestResources

      - name: Debug noreply.json presence
        run: |
          find build/resources/test -name "noreply.json" || echo "noreply.json not found in build/resources/test"

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test With Gradle
        run: ./gradlew --info test -Dspring.profiles.active=test
